### ISSUE TITLE
how to get train/val/text.txt for PG19

### ISSUE THREAD

**Issue by sustcsonglin** [Shark-NLP/CAB#2]
Hi,

I have a question about PG-19 data processing. It is said that 

> Integrate the downloaded [PG-19](https://github.com/deepmind/pg19) dataset into train.txt, vaild.txt, and text.txt. We use GPT-2 tokenizer to convert text into tokens as follows:

but i cannot find train/valid/test.txt file. how did you do such preprocssing to merge lots of txt into a single file?

**Comment by z562** [comment]
We downloaded the PG-19 dataset, and its file tree is shown as follows: 
```
- train
  - 10.txt
  - 100.txt
  - 10002.txt 
  .
  .
  .
- test
- validation
```
We concatenate the contents of each file in the 'train/' directory to form 'train.txt'.
